// ARRAY MASTODONTICO DE JSONS
const pokedex = [
    {
        dexNum:1,
        nombre:"Bulbasur",
        tipo1:"Grass",
        tipo2:"Poison",
        especie:"Seed Pokemon",
        altura:"0.7 m",
        peso:"6.9 kg",
        gruposHuevo:["Monster","Grass"],
        genero: new Genero(88.1,11.9),
        habilidades:["Overgrow","Chlorophyll"],
        stats:new Stats(5,5,5,7,7,5),
        velocidades:new Velocidades(4,null,null,null,null),
        atributos:new Atributos(-1,1),
        skills:["Acro +4","Athl +4","End +2","Per +2","Sur +6"],
        caracteristicas:["Size - Small","Hatchrate - Med"],
        evolution:"Ivysaur - 3"
    },
    {
        dexNum:2,
        nombre:"Ivysaur",
        tipo1:"Grass",
        tipo2:"Poison",
        especie:"Seed Pokemon",
        altura:"1 m",
        peso:"13 kg",
        gruposHuevo:["Monster","Grass"],
        genero: new Genero(88.1,11.9),
        habilidades:["Overgrow","Chlorophyll"],
        stats:new Stats(6,6,6,8,8,6),
        velocidades:new Velocidades(4,null,null,null,null),
        atributos:new Atributos(0,2),
        skills:["Acro +6","Athl +6","End +6","Per +6","Sur +8"],
        caracteristicas:["Size - Medium"],
        evolution:"Venusaur - 6"
    },
    {
        dexNum:3,
        nombre:"Venusaur",
        tipo1:"Grass",
        tipo2:"Poison",
        especie:"Seed Pokemon",
        altura:"2 m",
        peso:"100 kg",
        gruposHuevo:["Monster","Grass"],
        genero: new Genero(88.1,11.9),
        habilidades:["Overgrow","Chlorophyll"],
        stats:new Stats(8,8,8,10,10,8),
        velocidades:new Velocidades(3,null,null,null,null),
        atributos:new Atributos(2,4),
        skills:["Acro +4","Athl +8","End +6","Insight +5","Per +8","Sur +8"],
        caracteristicas:["Size - Large"],
        evolution:""
    },
    {
        dexNum:4,
        nombre:"Charmander",
        tipo1:"Fire",
        tipo2:"",
        especie:"Lizard Pokemon",
        altura:"0.6 m",
        peso:"8.5 kg",
        gruposHuevo:["Monster","Dragon"],
        genero: new Genero(88.1,11.9),
        habilidades:["Blaze","Solar Power"],
        stats:new Stats(4,5,4,6,5,7),
        velocidades:new Velocidades(3,null,null,null,null),
        atributos:new Atributos(-1,1),
        skills:["Acro +6","Athl +2","End +4","Per +2","Sur +4"],
        caracteristicas:["Size - Small","Luminous","Firestarter","Hatchrate - Med"],
        evolution:"Charmeleon - 3"
    },
    {
        dexNum:5,
        nombre:"Charmeleon",
        tipo1:"Fire",
        tipo2:"",
        especie:"Flame Pokemon",
        altura:"1.1 m",
        peso:"19 kg",
        gruposHuevo:["Monster","Dragon"],
        genero: new Genero(88.1,11.9),
        habilidades:["Blaze","Solar Power"],
        stats:new Stats(6,6,6,8,7,8),
        velocidades:new Velocidades(3,null,null,null,null),
        atributos:new Atributos(1,2),
        skills:["Acro +8","Athl +8","End +6","Per +6","Sur +6"],
        caracteristicas:["Size - Medium","Luminous","Firestarter"],
        evolution:"Charizard - 7"
    },
    {
        dexNum:6,
        nombre:"Charizard",
        tipo1:"Fire",
        tipo2:"Flying",
        especie:"Flame Pokemon",
        altura:"1.7 m",
        peso:"90.5 kg",
        gruposHuevo:["Monster","Dragon"],
        genero: new Genero(88.1,11.9),
        habilidades:["Blaze","Solar Power"],
        stats:new Stats(8,8,8,10,9,10),
        velocidades:new Velocidades(2,3,null,null,null),
        atributos:new Atributos(2,3),
        skills:["Acro +8","Athl +6","End +4","Intim +7","Per +8","Sur +6"],
        caracteristicas:["Size - Medium","Luminous","Firestarter"],
        evolution:""
    },
    {
        dexNum:7,
        nombre:"Squirtle",
        tipo1:"Water",
        tipo2:"",
        especie:"Tiny Turtle Pokemon",
        altura:"0.5 m",
        peso:"9 kg",
        gruposHuevo:["Monster","Water 1"],
        genero: new Genero(88.1,11.9),
        habilidades:["Torrent","Rain Dish"],
        stats:new Stats(4,5,7,5,6,4),
        velocidades:new Velocidades(4,null,null,4,null),
        atributos:new Atributos(-1,1),
        skills:["Acro +6","Athl +2","End +4","Per +2","Sur +4"],
        caracteristicas:["Size - Small","Wellspring","Hatchrate - Med"],
        evolution:"Wartortle - 3"
    },
    {
        dexNum:8,
        nombre:"Wartortle",
        tipo1:"Water",
        tipo2:"",
        especie:"Turtle Pokemon",
        altura:"1 m",
        peso:"22.5 kg",
        gruposHuevo:["Monster","Water 1"],
        genero: new Genero(88.1,11.9),
        habilidades:["Torrent","Rain Dish"],
        stats:new Stats(6,6,8,7,8,6),
        velocidades:new Velocidades(3,null,null,4,null),
        atributos:new Atributos(1,2),
        skills:["Acro +8","Athl +8","End +6","Per +6","Sur +6"],
        caracteristicas:["Size - Medium","Wellspring"],
        evolution:"Blastoise - 7"
    },
    {
        dexNum:9,
        nombre:"Blastoise",
        tipo1:"Water",
        tipo2:"",
        especie:"Shellfish Pokemon",
        altura:"1.6 m",
        peso:"85.5 kg",
        gruposHuevo:["Monster","Water 1"],
        genero: new Genero(88.1,11.9),
        habilidades:["Torrent","Rain Dish"],
        stats:new Stats(8,8,10,9,11,8),
        velocidades:new Velocidades(2,null,null,5,null),
        atributos:new Atributos(2,3),
        skills:["Acro +5","Athl +8","End +8","Ins +6","Per +6","Sur +6"],
        caracteristicas:["Size - Medium","Wellspring"],
        evolution:""
    },
    {
        dexNum:10,
        nombre:"Caterpie",
        tipo1:"Bug",
        tipo2:"",
        especie:"Worm Pokemon",
        altura:"0.3 m",
        peso:"2.9 kg",
        gruposHuevo:["Bug"],
        genero: new Genero(),
        habilidades:["Shield Dust","Run Away"],
        stats:new Stats(5,3,4,2,2,5),
        velocidades:new Velocidades(2,null,null,null,2),
        atributos:new Atributos(-2,-2),
        skills:["Dec +4","Ins +2","Per +4","Ste +4"],
        caracteristicas:["Size - Small","Bugsilk","Hatchrate - Short"],
        evolution:"Metapod - 1"
    },
    {
        dexNum:11,
        nombre:"Metapod",
        tipo1:"Bug",
        tipo2:"",
        especie:"Cocoon Pokemon",
        altura:"0.7 m",
        peso:"9.9 kg",
        gruposHuevo:["Bug"],
        genero: new Genero(),
        habilidades:["Shed Skin"],
        stats:new Stats(5,2,6,3,3,3),
        velocidades:new Velocidades(0,null,null,null,null),
        atributos:new Atributos(-1,-3),
        skills:["Dec +6","Ins +4","Per +4","Ste +8"],
        caracteristicas:["Size - Small","Bugsilk"],
        evolution:"Butterfree - 2"
    },
    {
        dexNum:12,
        nombre:"Butterfree",
        tipo1:"Bug",
        tipo2:"Flying",
        especie:"Butterfly Pokemon",
        altura:"1.1 m",
        peso:"32 kg",
        gruposHuevo:["Bug"],
        genero: new Genero(),
        habilidades:["Compound Eyes","Tinted Lens"],
        stats:new Stats(6,5,5,9,8,7),
        velocidades:new Velocidades(0,3,null,null,null),
        atributos:new Atributos(2,-1),
        skills:["Acro +6","Dec +6","Ins +6","Per +8","Psy +6"],
        caracteristicas:["Size - Medium","Bugsilk"],
        evolution:""
    },
    {
        dexNum:13,
        nombre:"Weedle",
        tipo1:"Bug",
        tipo2:"Poison",
        especie:"Hairy Pokemon",
        altura:"0.3 m",
        peso:"3.2 kg",
        gruposHuevo:["Bug"],
        genero: new Genero(),
        habilidades:["Shield Dust","Run Away"],
        stats:new Stats(4,4,3,2,2,5),
        velocidades:new Velocidades(2,null,null,null,2),
        atributos:new Atributos(-2,-2),
        skills:["Acro +4","Per +4","Ste +4","Sur +2"],
        caracteristicas:["Size - Small","Bugsilk","Hatchrate -Short"],
        evolution:"Kakuna - 1"
    },
    {
        dexNum:14,
        nombre:"Kakuna",
        tipo1:"Bug",
        tipo2:"Poison",
        especie:"Cocoon Pokemon",
        altura:"0.6 m",
        peso:"10 kg",
        gruposHuevo:["Bug"],
        genero: new Genero(),
        habilidades:["Shed Skin"],
        stats:new Stats(5,3,5,3,3,4),
        velocidades:new Velocidades(-1,null,null,null,2),
        atributos:new Atributos(-1,-3),
        skills:["Dec +4","Per +6","Ste +8","Sur +4"],
        caracteristicas:["Size - Small","Bugsilk"],
        evolution:"Beedrill - 2"
    },
    {
        dexNum:15,
        nombre:"Beedrill",
        tipo1:"Bug",
        tipo2:"Poison",
        especie:"Poison Bee Pokemon",
        altura:"1 m",
        peso:"29.5 kg",
        gruposHuevo:["Bug"],
        genero: new Genero(),
        habilidades:["Swarm","Sniper"],
        stats:new Stats(7,9,4,5,8,8),
        velocidades:new Velocidades(null,3,null,null,null),
        atributos:new Atributos(-1,1),
        skills:["Acro +10","Intim +8","Per +10","Sur +6"],
        caracteristicas:["Size - Medium","Bugsilk"],
        evolution:""
    },
    {
        dexNum:16,
        nombre:"Pidgey",
        tipo1:"Normal",
        tipo2:"Flying",
        especie:"Tiny Bird Pokemon",
        altura:"0.3 m",
        peso:"1.8 kg",
        gruposHuevo:["Flying"],
        genero: new Genero(),
        habilidades:["Keen Eye","Tangled Feet","Big Pecks"],
        stats:new Stats(4,5,4,4,4,6),
        velocidades:new Velocidades(0,3,null,null,null),
        atributos:new Atributos(-1,-1),
        skills:["Acro +5","Athl +4","End +2","Per +4","Sur +4"],
        caracteristicas:["Size - Small","Hatchrate - Med"],
        evolution:"Pidgeotto - 3"
    },
    {
        dexNum:17,
        nombre:"Pidgeotto",
        tipo1:"Normal",
        tipo2:"Flying",
        especie:"Bird Pokemon",
        altura:"1.1 m",
        peso:"30 kg",
        gruposHuevo:["Flying"],
        genero: new Genero(),
        habilidades:["Keen Eye","Tangled Feet","Big Pecks"],
        stats:new Stats(6,6,6,5,5,7),
        velocidades:new Velocidades(0,4,null,null,null),
        atributos:new Atributos(0,1),
        skills:["Acro +7","Athl +6","End +4","Per +6","Sur +4"],
        caracteristicas:["Size - Medium"],
        evolution:"Pidgeot - 7"
    },
    {
        dexNum:18,
        nombre:"Pidgeot",
        tipo1:"Normal",
        tipo2:"Flying",
        especie:"Bird Pokemon",
        altura:"1.5 m",
        peso:"39.5 kg",
        gruposHuevo:["Flying"],
        genero: new Genero(),
        habilidades:["Keen Eye","Tangled Feet","Big Pecks"],
        stats:new Stats(8,8,8,7,7,10),
        velocidades:new Velocidades(0,4,null,null,null),
        atributos:new Atributos(0,2),
        skills:["Acro +9","Athl +7","End +5","Per +8","Sur +6"],
        caracteristicas:["Size - Medium"],
        evolution:""
    },
    {
        dexNum:19,
        nombre:"Rattata",
        tipo1:"Normal",
        tipo2:"",
        especie:"Mouse Pokemon",
        altura:"0.3 m",
        peso:"3.5 kg",
        gruposHuevo:["Field"],
        genero: new Genero(),
        habilidades:["Run Away","Guts","Hustle"],
        stats:new Stats(3,6,4,3,4,7),
        velocidades:new Velocidades(3,null,null,null,null),
        atributos:new Atributos(0,-2),
        skills:["Acro +5","Athl +4","Per +4","Ste +6","Sur +4"],
        caracteristicas:["Size - Small","Stealthy","Hatchrate - Short"],
        evolution:"Raticate - 4"
    },
    {
        dexNum:20,
        nombre:"Raticate",
        tipo1:"Normal",
        tipo2:"",
        especie:"Mouse Pokemon",
        altura:"0.7 m",
        peso:"18.5 kg",
        gruposHuevo:["Field"],
        genero: new Genero(),
        habilidades:["Run Away","Guts","Hustle"],
        stats:new Stats(6,8,6,5,7,10),
        velocidades:new Velocidades(2,null,null,null,null),
        atributos:new Atributos(1,0),
        skills:["Acro +6","Athl +4","Per +6","Ste +8","Sur +6"],
        caracteristicas:["Size - Small","Stealthy"],
        evolution:""
    },
    {
        dexNum:21,
        nombre:"Spearow",
        tipo1:"Normal",
        tipo2:"Flying",
        especie:"Tiny Bird Pokemon",
        altura:"0.3 m",
        peso:"2 kg",
        gruposHuevo:["Flying"],
        genero: new Genero(),
        habilidades:["Keen Eye","Sniper"],
        stats:new Stats(4,6,3,3,3,7),
        velocidades:new Velocidades(0,3,null,null,null),
        atributos:new Atributos(-1,-1),
        skills:["Acro +5","End +4","Per +6","Sur +3"],
        caracteristicas:["Size - Small","Hatchrate - Med"],
        evolution:"Fearow - 4"
    },
    {
        dexNum:22,
        nombre:"Fearow",
        tipo1:"Normal",
        tipo2:"Flying",
        especie:"Beak Pokemon",
        altura:"1.2 m",
        peso:"38 kg",
        gruposHuevo:["Flying"],
        genero: new Genero(),
        habilidades:["Keen Eye","Sniper"],
        stats:new Stats(7,9,7,6,6,10),
        velocidades:new Velocidades(null,4,null,null,null),
        atributos:new Atributos(-1,3),
        skills:["Acro +8","End +10","Per +8","Sur +4"],
        caracteristicas:["Size - Medium"],
        evolution:""
    },
    {
        dexNum:23,
        nombre:"Ekans",
        tipo1:"Poison",
        tipo2:"",
        especie:"Snake Pokemon",
        altura:"2 m",
        peso:"6.9 kg",
        gruposHuevo:["Field","Dragon"],
        genero: new Genero(),
        habilidades:["Intimidate","Shed Skin","Unnerve"],
        stats:new Stats(4,6,4,4,5,6),
        velocidades:new Velocidades(2,null,0,1,null),
        atributos:new Atributos(-2,-2),
        skills:["Intim +6","Per +4","Ste +4","Sur +4"],
        caracteristicas:["Size - Small","Stealthy","Hatchrate - Med"],
        evolution:"Arbok - 4"
    },
    {
        dexNum:24,
        nombre:"Arbok",
        tipo1:"Poison",
        tipo2:"",
        especie:"Cobra Pokemon",
        altura:"3.5 m",
        peso:"65 kg",
        gruposHuevo:["Field","Dragon"],
        genero: new Genero(),
        habilidades:["Intimidate","Shed Skin","Unnerve"],
        stats:new Stats(6,10,7,7,8,8),
        velocidades:new Velocidades(3,null,null,null,null),
        atributos:new Atributos(0,3),
        skills:["Intim +10","Per +6","Ste +6","Sur +6"],
        caracteristicas:["Size - Medium","Stealthy"],
        evolution:""
    },
    {
        dexNum:25,
        nombre:"Pikachu",
        tipo1:"Electric",
        tipo2:"",
        especie:"Mouse Pokemon",
        altura:"0.4 m",
        peso:"6 kg",
        gruposHuevo:["Field","Fairy"],
        genero: new Genero(),
        habilidades:["Static","Lightning Rod"],
        stats:new Stats(4,6,4,5,5,9),
        velocidades:new Velocidades(2,null,null,null,null),
        atributos:new Atributos(1,-2),
        skills:["Acro +6","Athl +4","Per +4","Sur +4"],
        caracteristicas:["Size - Small","Generator","Hatchrate - Short"],
        evolution:"Raichu - Thunderstone"
    },
    {
        dexNum:26,
        nombre:"Raichu",
        tipo1:"Electric",
        tipo2:"",
        especie:"Mouse Pokemon",
        altura:"0.8 m",
        peso:"30 kg",
        gruposHuevo:["Field","Fairy"],
        genero: new Genero(),
        habilidades:["Static","Lightning Rod"],
        stats:new Stats(6,9,6,9,8,11),
        velocidades:new Velocidades(2,null,null,null,null),
        atributos:new Atributos(1,-1),
        skills:["Acro +8","Athl +4","Per +6","Sur +4", "Ins +5"],
        caracteristicas:["Size - Medium","Generator"],
        evolution:""
    },
    {
        dexNum:27,
        nombre:"Sandshrew",
        tipo1:"Ground",
        tipo2:"",
        especie:"Mouse Pokemon",
        altura:"0.6 m",
        peso:"12 kg",
        gruposHuevo:["Field"],
        genero: new Genero(),
        habilidades:["Sand Veild","Sand Rush"],
        stats:new Stats(5,8,9,2,3,4),
        velocidades:new Velocidades(3,null,2,null,0),
        atributos:new Atributos(-1,-2),
        skills:["Athl +4","End +5","Per +4","Ste +4","Sur +2"],
        caracteristicas:["Size - Small","Tremorsense 2","Hatchrate - Med"],
        evolution:"Sandslash - 4"
    },
    {
        dexNum:28,
        nombre:"Sandslash",
        tipo1:"Ground",
        tipo2:"",
        especie:"Mouse Pokemon",
        altura:"1 m",
        peso:"29.5 kg",
        gruposHuevo:["Field"],
        genero: new Genero(),
        habilidades:["Sand Veild","Sand Rush"],
        stats:new Stats(8,10,11,5,6,7),
        velocidades:new Velocidades(3,null,3,null,1),
        atributos:new Atributos(0,2),
        skills:["Acro +6","Athl +4","End +6","Per +6","Ste +4","Sur +6"],
        caracteristicas:["Size - Medium","Tremorsense 2"],
        evolution:""
    },
    {
        dexNum:29,
        nombre:"Nidoran ♀",
        tipo1:"Poison",
        tipo2:"",
        especie:"Poison Pin Pokemon",
        altura:"0.4 m",
        peso:"7 kg",
        gruposHuevo:["Monster","Field"],
        genero: new Genero(0,100),
        habilidades:["Poison Point","Rivalry","Hustle"],
        stats:new Stats(6,5,5,4,4,4),
        velocidades:new Velocidades(3,null,null,null,null),
        atributos:new Atributos(-1,-2),
        skills:["End +4","Ins +3","Per +4","Sur +4"],
        caracteristicas:["Size - Small","Hatchrate - Med"],
        evolution:"Nidorina - 3"
    },
    {
        dexNum:30,
        nombre:"Nidorina",
        tipo1:"Poison",
        tipo2:"",
        especie:"Poison Pin Pokemon",
        altura:"0.8 m",
        peso:"20 kg",
        gruposHuevo:["Monster","Field"],
        genero: new Genero(0,100),
        habilidades:["Poison Point","Rivalry","Hustle"],
        stats:new Stats(7,6,7,6,6,6),
        velocidades:new Velocidades(3,null,null,null,null),
        atributos:new Atributos(0,0),
        skills:["Athl +4","End +6","Ins +4","Per +6","Sur +6"],
        caracteristicas:["Size - Medium"],
        evolution:"Nidoqueen - Moonstone"
    },
    {
        dexNum:31,
        nombre:"Nidoqueen",
        tipo1:"Poison",
        tipo2:"Ground",
        especie:"Drill Pokemon",
        altura:"1.3 m",
        peso:"60 kg",
        gruposHuevo:["Monster","Field"],
        genero: new Genero(0,100),
        habilidades:["Poison Point","Rivalry","Sheer Force"],
        stats:new Stats(9,9,9,8,9,8),
        velocidades:new Velocidades(2,null,null,null,null),
        atributos:new Atributos(0,3),
        skills:["Athl +8","End +8","Ins +6","Per +7","Sur +7"],
        caracteristicas:["Size - Medium"],
        evolution:""
    },
    {
        dexNum:32,
        nombre:"Nidoran ♂",
        tipo1:"Poison",
        tipo2:"",
        especie:"Poison Pin Pokemon",
        altura:"0.5 m",
        peso:"9 kg",
        gruposHuevo:["Monster","Field"],
        genero: new Genero(100,0),
        habilidades:["Poison Point","Rivalry","Hustle"],
        stats:new Stats(5,6,4,4,4,5),
        velocidades:new Velocidades(3,null,null,null,null),
        atributos:new Atributos(-1,-2),
        skills:["End +4","Ins +3","Per +4","Sur +4"],
        caracteristicas:["Size - Small","Hatchrate - Med"],
        evolution:"Nidorino - 3"
    },
    {
        dexNum:33,
        nombre:"Nidorino",
        tipo1:"Poison",
        tipo2:"",
        especie:"Poison Pin Pokemon",
        altura:"0.9 m",
        peso:"19.5 kg",
        gruposHuevo:["Monster","Field"],
        genero: new Genero(100,0),
        habilidades:["Poison Point","Rivalry","Hustle"],
        stats:new Stats(6,7,6,6,6,7),
        velocidades:new Velocidades(3,null,null,null,null),
        atributos:new Atributos(0,0),
        skills:["Athl +4","End +6","Ins +4","Per +6","Sur +6"],
        caracteristicas:["Size - Small"],
        evolution:"Nidoking - Moonstone"
    },
    {
        dexNum:34,
        nombre:"Nidoking",
        tipo1:"Poison",
        tipo2:"Ground",
        especie:"Drill Pokemon",
        altura:"1.4 m",
        peso:"62 kg",
        gruposHuevo:["Monster","Field"],
        genero: new Genero(100,0),
        habilidades:["Poison Point","Rivalry","Sheer Force"],
        stats:new Stats(8,10,8,9,8,9),
        velocidades:new Velocidades(3,null,null,null,null),
        atributos:new Atributos(0,3),
        skills:["Athl +8","End +8","Ins +6","Per +7","Sur +7"],
        caracteristicas:["Size - Medium"],
        evolution:""
    },
    {
        dexNum:35,
        nombre:"Clefairy",
        tipo1:"Fairy",
        tipo2:"",
        especie:"Fairy Pokemon",
        altura:"0.6 m",
        peso:"7.5 kg",
        gruposHuevo:["Fairy"],
        genero: new Genero(24.6,75.4),
        habilidades:["Cute Charm","Magic Guard","Friend Guard"],
        stats:new Stats(7,4,5,6,7,3),
        velocidades:new Velocidades(3,null,null,null,null),
        atributos:new Atributos(2,-2),
        skills:["Acro +4","Ins +6","Per +4","Ste +4"],
        caracteristicas:["Size - Small","Hatchrate - Short"],
        evolution:"Clefable - Moonstone"
    },
    {
        dexNum:36,
        nombre:"Clefable",
        tipo1:"Fairy",
        tipo2:"",
        especie:"Fairy Pokemon",
        altura:"1.3 m",
        peso:"40 kg",
        gruposHuevo:["Fairy"],
        genero: new Genero(24.6,75.4),
        habilidades:["Cute Charm","Magic Guard","Unaware"],
        stats:new Stats(9,7,7,10,9,6),
        velocidades:new Velocidades(3,null,null,null,null),
        atributos:new Atributos(2,1),
        skills:["Acro +4","Ins +9","Per +6","Ste +6"],
        caracteristicas:["Size - Medium"],
        evolution:""
    },
    {
        dexNum:37,
        nombre:"Vulpix",
        tipo1:"Fire",
        tipo2:"",
        especie:"Fox Pokemon",
        altura:"0.6 m",
        peso:"9.9 kg",
        gruposHuevo:["Field"],
        genero: new Genero(24.6,75.4),
        habilidades:["Flash Fire","Drought"],
        stats:new Stats(4,4,4,5,7,7),
        velocidades:new Velocidades(3,null,null,null,null),
        atributos:new Atributos(-1,-2),
        skills:["Acro +6","Per +4","Ste +4","Sur +4"],
        caracteristicas:["Size - Small","Hatchrate - Med"],
        evolution:"Ninetales - Firestone"
    },
    {
        dexNum:38,
        nombre:"Ninetales",
        tipo1:"Fire",
        tipo2:"",
        especie:"Fox Pokemon",
        altura:"1.1 m",
        peso:"19.9 kg",
        gruposHuevo:["Field"],
        genero: new Genero(24.6,75.4),
        habilidades:["Flash Fire","Drought"],
        stats:new Stats(7,8,8,8,10,10),
        velocidades:new Velocidades(3,null,null,null,null),
        atributos:new Atributos(2,2),
        skills:["Acro +10","Ins +5","Per +6","Ste +6","Sur +4"],
        caracteristicas:["Size - Medium"],
        evolution:""
    },
    {
        dexNum:39,
        nombre:"Jigglypuff",
        tipo1:"Normal",
        tipo2:"Fairy",
        especie:"Ballon Pokemon",
        altura:"0.5 m",
        peso:"5.5 kg",
        gruposHuevo:["Fairy"],
        genero: new Genero(24.6,75.4),
        habilidades:["Cute Charm","Competitive","Friend Guard"],
        stats:new Stats(12,5,2,5,3,2),
        velocidades:new Velocidades(4,null,null,null,null),
        atributos:new Atributos(2,-2),
        skills:["Acro +6","Ins +5","Per +4","Ste +4"],
        caracteristicas:["Size - Small","Infatable","Hatchrate - Short"],
        evolution:"Wigglytuff - Moonstone"
    },
    {
        dexNum:40,
        nombre:"Wigglytuff",
        tipo1:"Normal",
        tipo2:"Fairy",
        especie:"Ballon Pokemon",
        altura:"1 m",
        peso:"12 kg",
        gruposHuevo:["Fairy"],
        genero: new Genero(24.6,75.4),
        habilidades:["Cute Charm","Competitive","Frisk"],
        stats:new Stats(14,7,5,9,5,5),
        velocidades:new Velocidades(4,null,null,null,null),
        atributos:new Atributos(2,1),
        skills:["Acro +9","Ins +7","F.Aid +4","Per +6","Ste +4"],
        caracteristicas:["Size - Medium","Infatable"],
        evolution:""
    },
    {
        dexNum:41,
        nombre:"Zubat",
        tipo1:"Poison",
        tipo2:"Flying",
        especie:"Bat Pokemon",
        altura:"0.8 m",
        peso:"7.5 kg",
        gruposHuevo:["Flying"],
        genero: new Genero(),
        habilidades:["Inner Focus","Infiltrator"],
        stats:new Stats(4,5,4,3,4,6),
        velocidades:new Velocidades(null,2,null,null,null),
        atributos:new Atributos(-3,-2),
        skills:["Acro +5","Per +8"],
        caracteristicas:["Size - Small","Blindsight 10","Hatchrate - Short"],
        evolution:"Golbat - 4"
    },
    {
        dexNum:42,
        nombre:"Golbat",
        tipo1:"Poison",
        tipo2:"Flying",
        especie:"Bat Pokemon",
        altura:"1.6 m",
        peso:"55 kg",
        gruposHuevo:["Flying"],
        genero: new Genero(),
        habilidades:["Inner Focus","Infiltrator"],
        stats:new Stats(8,8,7,7,8,9),
        velocidades:new Velocidades(0,3,null,null,null),
        atributos:new Atributos(-1,2),
        skills:["Acro +7","Per +10"],
        caracteristicas:["Size - Medium","Blindsight 10"],
        evolution:"Crobat - Loyalty 5"
    },
    {
        dexNum:43,
        nombre:"Oddish",
        tipo1:"Grass",
        tipo2:"Poison",
        especie:"Weed Pokemon",
        altura:"0.5 m",
        peso:"5.4 kg",
        gruposHuevo:["Grass"],
        genero: new Genero(),
        habilidades:["Chlorophyll","Run Away"],
        stats:new Stats(5,5,6,8,7,3),
        velocidades:new Velocidades(3,null,0,null,null),
        atributos:new Atributos(-1,-2),
        skills:["Dec +3","End +3","Per +4","Ste +6"],
        caracteristicas:["Size - Small","Hatchrate - Med"],
        evolution:"Gloom - 4"
    },
    {
        dexNum:44,
        nombre:"Gloom",
        tipo1:"Grass",
        tipo2:"Poison",
        especie:"Weed Pokemon",
        altura:"0.8 m",
        peso:"8.6 kg",
        gruposHuevo:["Grass"],
        genero: new Genero(),
        habilidades:["Chlorophyll","Stench"],
        stats:new Stats(6,7,7,9,8,4),
        velocidades:new Velocidades(3,null,0,null,null),
        atributos:new Atributos(0,-2),
        skills:["Dec +4","End +4","Per +4","Ste +8"],
        caracteristicas:["Size - Small"],
        evolution:"Vileplume - Leafstone / Bellossom - Sunstone"
    },
    {
        dexNum:45,
        nombre:"Vileplume",
        tipo1:"Grass",
        tipo2:"Poison",
        especie:"Flower Pokemon",
        altura:"1.2 m",
        peso:"18.6 kg",
        gruposHuevo:["Grass"],
        genero: new Genero(),
        habilidades:["Chlorophyll","Effect Spore"],
        stats:new Stats(8,8,9,11,9,5),
        velocidades:new Velocidades(3,null,0,null,null),
        atributos:new Atributos(1,-1),
        skills:["Dec +3","End +4","Per +6","Ste +10"],
        caracteristicas:["Size - Medium","Enticing Odor"],
        evolution:""
    },
    {
        dexNum:46,
        nombre:"Paras",
        tipo1:"Bug",
        tipo2:"Grass",
        especie:"Mushroom Pokemon",
        altura:"0.3 m",
        peso:"5.4 kg",
        gruposHuevo:["Bug","Grass"],
        genero: new Genero(),
        habilidades:["Effect Spore","Dry Skin","Damp"],
        stats:new Stats(4,7,6,5,6,3),
        velocidades:new Velocidades(3,null,1,null,null),
        atributos:new Atributos(-2,-1),
        skills:["Per +6","Ste +5","Sur +4"],
        caracteristicas:["Size - Small","Hatchrate - Med"],
        evolution:"Parasect - 5"
    },
    {
        dexNum:47,
        nombre:"Parasect",
        tipo1:"Bug",
        tipo2:"Grass",
        especie:"Mushroom Pokemon",
        altura:"1 m",
        peso:"29.5 kg",
        gruposHuevo:["Bug","Grass"],
        genero: new Genero(),
        habilidades:["Effect Spore","Dry Skin","Damp"],
        stats:new Stats(6,10,8,6,8,3),
        velocidades:new Velocidades(5,null,1,null,null),
        atributos:new Atributos(-2,0),
        skills:["Per +8","Ste +6","Sur +6"],
        caracteristicas:["Size - Medium"],
        evolution:""
    },
    {
        dexNum:48,
        nombre:"Venonat",
        tipo1:"Bug",
        tipo2:"Poison",
        especie:"Insect Pokemon",
        altura:"1 m",
        peso:"30 kg",
        gruposHuevo:["Bug"],
        genero: new Genero(),
        habilidades:["Compound Eyes","Tinted Lens","Run Away"],
        stats:new Stats(6,6,5,4,6,5),
        velocidades:new Velocidades(3,null,null,null,null),
        atributos:new Atributos(-1,-1),
        skills:["Acro +5","Per +7","Sur +4"],
        caracteristicas:["Size - Medium","Hatchrate - Med"],
        evolution:"Venomoth - 6"
    },
    {
        dexNum:49,
        nombre:"Venomoth",
        tipo1:"Bug",
        tipo2:"Poison",
        especie:"Poison Moth Pokemon",
        altura:"1.5 m",
        peso:"12.5 kg",
        gruposHuevo:["Bug"],
        genero: new Genero(),
        habilidades:["Shield Dust","Tinted Lens","Wonder Skin"],
        stats:new Stats(7,7,6,9,8,9),
        velocidades:new Velocidades(null,2,null,null,null),
        atributos:new Atributos(0,0),
        skills:["Acro +7","Per +9","Psy +6","Sur +6"],
        caracteristicas:["Size - Medium"],
        evolution:""
    },
    {
        dexNum:50,
        nombre:"Diglett",
        tipo1:"Ground",
        tipo2:"",
        especie:"Mole Pokemon",
        altura:"0.2 m",
        peso:"0.8 kg",
        gruposHuevo:["Field"],
        genero: new Genero(),
        habilidades:["Sand Veil","Arena Trap","Sand Force"],
        stats:new Stats(1,6,3,4,5,10),
        velocidades:new Velocidades(null,null,2,null,null),
        atributos:new Atributos(-2,-3),
        skills:["End +4","Per +4","Ste +4","Sur +4"],
        caracteristicas:["Size - Small","Tremorsense 4","Hatchrate - Med"],
        evolution:"Dugtrio - 5"
    },
    {
        dexNum:51,
        nombre:"Dugtrio",
        tipo1:"Ground",
        tipo2:"",
        especie:"Mole Pokemon",
        altura:"0.7 m",
        peso:"33.3 kg",
        gruposHuevo:["Field"],
        genero: new Genero(),
        habilidades:["Sand Veil","Arena Trap","Sand Force"],
        stats:new Stats(4,10,5,5,7,12),
        velocidades:new Velocidades(null,null,2,null,null),
        atributos:new Atributos(-1,0),
        skills:["End +6","Per +8","Ste +4","Sur +6"],
        caracteristicas:["Size - Medium","Tremorsense 6"],
        evolution:""
    },
    {
        dexNum: 52,
        nombre: "Meowth",
        tipo1: "Normal",
        tipo2: "",
        especie: "Scratch Cat Pokémon",
        altura: "0.4 m",
        peso: "4.2 kg",
        gruposHuevo: ["Field"],
        genero: new Genero(),
        habilidades: ["Pickup", "Technician", "Unnerve"],
        stats:new Stats(4,5,4,4,4,9),
        velocidades:new Velocidades(2,null,null,null,null),
        atributos:new Atributos(1,-1),
        skills:["Acro +4","Athl +4","Per +5","Ste +6","Sur +4"],
        caracteristicas:["Size - Small","Stealthy","Hatchrate - Med"],
        evolution: "Persian - 5"
    },
    {
        dexNum: 53,
        nombre: "Persian",
        tipo1: "Normal",
        tipo2: "",
        especie: "Classy Cat Pokémon",
        altura: "1.0 m",
        peso: "32.0 kg",
        gruposHuevo: ["Field"],
        genero: new Genero(),
        habilidades: ["Limber", "Technician", "Unnerve"],
        stats:new Stats(7,7,6,7,7,12),
        velocidades:new Velocidades(1,null,null,null,null),
        atributos:new Atributos(2,1),
        skills:["Acro +8","Athl +4","Per +6","Ste +8","Sur +4"],
        caracteristicas:["Size - Medium", "Stealthy"],
        evolution: ""
    },
    {
        dexNum: 54,
        nombre: "Psyduck",
        tipo1: "Water",
        tipo2: "",
        especie: "Duck Pokémon",
        altura: "0.8 m",
        peso: "19.6 kg",
        gruposHuevo: ["Water 1", "Field"],
        genero: new Genero(),
        habilidades: ["Damp", "Cloud Nine", "Swift Swim"],
        stats:new Stats(5,5,5,7,5,6),
        velocidades:new Velocidades(2,null,null,4,null),
        atributos:new Atributos(0,-2),
        skills:["Athl +3","Ins +4","Psy +6"],
        caracteristicas:["Size - Small","Hatchrate - Med"],
        evolution: "Golduck - 6"
    },
    {
        dexNum: 55,
        nombre: "Golduck",
        tipo1: "Water",
        tipo2: "",
        especie: "Duck Pokémon",
        altura: "1.7 m",
        peso: "76.6 kg",
        gruposHuevo: ["Water 1", "Field"],
        genero: new Genero(),
        habilidades: ["Damp", "Cloud Nine", "Swift Swim"],
        stats:new Stats(8,8,8,10,8,9),
        velocidades:new Velocidades(2,null,null,3,null),
        atributos:new Atributos(3,0),
        skills:["Athl +7","Ins +6","Psy +8"],
        caracteristicas:["Size - Medium"],
        evolution: ""
    },
    {
        dexNum: 56,
        nombre: "Mankey",
        tipo1: "Fighting",
        tipo2: "",
        especie: "Pig Monkey Pokémon",
        altura: "0.5 m",
        peso: "28.0 kg",
        gruposHuevo: ["Field"],
        genero: new Genero(),
        habilidades: ["Vital Spirit", "Anger Point", "Defiant"],
        stats:new Stats(4,8,4,4,5,7),
        velocidades:new Velocidades(3,null,null,null,3),
        atributos:new Atributos(-1,-1),
        skills:["Acro +7","Athl +5","Per +4"],
        caracteristicas:["Size - Small","Hatchrate - Med"],
        evolution: "Primeape - 5"
    },
    {
        dexNum: 57,
        nombre: "Primeape",
        tipo1: "Fighting",
        tipo2: "",
        especie: "Pig Monkey Pokémon",
        altura: "1.0 m",
        peso: "32.0 kg",
        gruposHuevo: ["Field"],
        genero: new Genero(),
        habilidades: ["Vital Spirit", "Anger Point", "Defiant"],
        stats:new Stats(7,11,6,6,7,10),
        velocidades:new Velocidades(1,null,null,null,1),
        atributos:new Atributos(0,3),
        skills:["Acro +10","Athl +7","Per +6","Train +6"],
        caracteristicas:["Size - Medium"],
        evolution: ""
    },
    {
        dexNum: 58,
        nombre: "Growlithe",
        tipo1: "Fire",
        tipo2: "",
        especie: "Puppy Pokémon",
        altura: "0.7 m",
        peso: "19.0 kg",
        gruposHuevo: ["Field"],
        genero: new Genero(75.4,24.6),
        habilidades: ["Intimidate", "Flash Fire", "Justified"],
        stats:new Stats(6,7,5,7,5,6),
        velocidades:new Velocidades(3,null,null,null,null),
        atributos:new Atributos(0,0),
        skills:["Athl +6","End +4","Intim +4","Per +6","Sur +6"],
        caracteristicas:["Size - Small","Tracker","Warm","Hatchrate - Med"],
        evolution: "Arcanine - Firestone"
    },
    {
        dexNum: 59,
        nombre: "Arcanine",
        tipo1: "Fire",
        tipo2: "",
        especie: "Legendary Pokémon",
        altura: "1.9 m",
        peso: "155.0 kg",
        gruposHuevo: ["Field"],
        genero: new Genero(75.4,24.6),
        habilidades: ["Intimidate", "Flash Fire", "Justified"],
        stats:new Stats(9,11,8,10,8,10),
        velocidades:new Velocidades(3,null,null,null,null),
        atributos:new Atributos(1,4),
        skills:["Athl +8","End +7","Intim +10","Per +7","Sur +7"],
        caracteristicas:["Size - Large","Tracker","Warm","Mountable"],
        evolution: ""
    },
    {
        dexNum: 60,
        nombre: "Poliwag",
        tipo1: "Water",
        tipo2: "",
        especie: "Tadpole Pokémon",
        altura: "0.6 m",
        peso: "12.4 kg",
        gruposHuevo: ["Water 1"],
        genero: new Genero(),
        habilidades: ["Water Absorb", "Damp", "Swift Swim"],
        stats:new Stats(4,5,4,4,4,9),
        velocidades:new Velocidades(-1,null,null,2,null),
        atributos:new Atributos(-1,-3),
        skills:["Acro +3","Per +4","Sur +4"],
        caracteristicas:["Size - Small","Hatchrate - Med"],
        evolution: "Poliwhirl - 5"
    },
    {
        dexNum: 61,
        nombre: "Poliwhirl",
        tipo1: "Water",
        tipo2: "",
        especie: "Tadpole Pokémon",
        altura: "1.0 m",
        peso: "20.0 kg",
        gruposHuevo: ["Water 1"],
        genero: new Genero(),
        habilidades: ["Water Absorb", "Damp", "Swift Swim"],
        stats:new Stats(7,7,7,5,5,9),
        velocidades:new Velocidades(1,null,null,2,null),
        atributos:new Atributos(0,1),
        skills:["Acro +6","End +5","Per +4","Sur +4"],
        caracteristicas:["Size - Medium"],
        evolution: "Poliwrath - Waterstone / Politoed - Sunstone"
    },
    {
        dexNum: 62,
        nombre: "Poliwrath",
        tipo1: "Water",
        tipo2: "Fighting",
        especie: "Tadpole Pokémon",
        altura: "1.3 m",
        peso: "54.0 kg",
        gruposHuevo: ["Water 1"],
        genero: new Genero(),
        habilidades: ["Water Absorb", "Damp", "Swift Swim"],
        stats:new Stats(9,10,10,7,9,7),
        velocidades:new Velocidades(3,null,null,3,null),
        atributos:new Atributos(0,3),
        skills:["Acro +8","Athl +8","End +6","Per +4","Train +6"],
        caracteristicas:["Size - Medium"],
        evolution: ""
    },
    {
        dexNum: 63,
        nombre: "Abra",
        tipo1: "Psychic",
        tipo2: "",
        especie: "Psi Pokémon",
        altura: "0.9 m",
        peso: "19.5 kg",
        gruposHuevo: ["Human-Like"],
        genero: new Genero(75.4,24.6),
        habilidades: ["Synchronize", "Inner Focus", "Magic Guard"],
        stats:new Stats(3,2,2,11,6,9),
        velocidades:new Velocidades(0,null,null,null,null),
        atributos:new Atributos(1,-2),
        skills:["Ins +5","Psy +6"],
        caracteristicas:["Size - Medium","Telekinetic","Telepath","Hatchrate - Med"],
        evolution: "Kadabra - 3"
    },
    {
        dexNum: 64,
        nombre: "Kadabra",
        tipo1: "Psychic",
        tipo2: "",
        especie: "Psi Pokémon",
        altura: "1.3 m",
        peso: "56.5 kg",
        gruposHuevo: ["Human-Like"],
        genero: new Genero(75.4,24.6),
        habilidades: ["Synchronize", "Inner Focus", "Magic Guard"],
        stats:new Stats(4,4,3,12,7,11),
        velocidades:new Velocidades(0,null,null,null,null),
        atributos:new Atributos(3,-1),
        skills:["Ins +7","Psy +9"],
        caracteristicas:["Size - Medium","Telekinetic","Telepath"],
        evolution: "Alakazam - ?"
    },
    {
        dexNum: 65,
        nombre: "Alakazam",
        tipo1: "Psychic",
        tipo2: "",
        especie: "Psi Pokémon",
        altura: "1.5 m",
        peso: "48.0 kg",
        gruposHuevo: ["Human-Like"],
        genero: new Genero(),
        habilidades: ["Synchronize", "Inner Focus", "Magic Guard"],
        stats:new Stats(6,5,5,14,10,12),
        velocidades:new Velocidades(1,null,null,null,null),
        atributos:new Atributos(6,-1),
        skills:["Ins +7","Psy +9"],
        caracteristicas:["Size - Medium","Telekinetic","Telepath"],
        evolution: ""
    },
    {
        dexNum: 66,
        nombre: "Machop",
        tipo1: "Fighting",
        tipo2: "",
        especie: "Superpower Pokémon",
        altura: "0.8 m",
        peso: "19.5 kg",
        gruposHuevo: ["Human-Like"],
        genero: new Genero(75.4,24.6),
        habilidades: ["Guts", "No Guard", "Steadfast"],
        stats:new Stats(7,8,5,4,4,4),
        velocidades:new Velocidades(3,null,null,null,null),
        atributos:new Atributos(-1,1),
        skills:["Athl +6","End +7","Train +4"],
        caracteristicas:["Size - Medium","Hatchrate - Med"],
        evolution: "Machoke - 5"
    },
    {
        dexNum: 67,
        nombre: "Machoke",
        tipo1: "Fighting",
        tipo2: "",
        especie: "Superpower Pokémon",
        altura: "1.5 m",
        peso: "70.5 kg",
        gruposHuevo: ["Human-Like"],
        genero: new Genero(75.4,24.6),
        habilidades: ["Guts", "No Guard", "Steadfast"],
        stats:new Stats(8,10,7,5,6,5),
        velocidades:new Velocidades(4,null,null,null,null),
        atributos:new Atributos(-1,3),
        skills:["Athl +6","End +7","PkCom +4","Train +4"],
        caracteristicas:["Size - Medium"],
        evolution: "Machamp - ?"
    },
    {
        dexNum: 68,
        nombre: "Machamp",
        tipo1: "Fighting",
        tipo2: "",
        especie: "Superpower Pokémon",
        altura: "1.6 m",
        peso: "130.0 kg",
        gruposHuevo: ["Human-Like"],
        genero: new Genero(75.4,24.6),
        habilidades: ["Guts", "No Guard", "Steadfast"],
        stats:new Stats(9,13,8,7,9,6),
        velocidades:new Velocidades(3,null,null,null,null),
        atributos:new Atributos(0,6),
        skills:["Athl +12","End +10","PkCom +6","Train +6"],
        caracteristicas:["Size - Medium"],
        evolution: ""
    },
    {
        dexNum: 69,
        nombre: "Bellsprout",
        tipo1: "Grass",
        tipo2: "Poison",
        especie: "Flower Pokémon",
        altura: "0.7 m",
        peso: "4.0 kg",
        gruposHuevo: ["Grass"],
        genero: new Genero(),
        habilidades: ["Chlorophyll", "Gluttony"],
        stats:new Stats(5,8,4,7,3,4),
        velocidades:new Velocidades(2,null,0,null,null),
        atributos:new Atributos(-2,-2),
        skills:["Dec +4","Per +2","Ste +4","Sur +4"],
        caracteristicas:["Size - Small","Hatchrate - Med"],
        evolution: "Weepinbell - 4"
    },
    {
        dexNum: 70,
        nombre: "Weepinbell",
        tipo1: "Grass",
        tipo2: "Poison",
        especie: "Flycatcher Pokémon",
        altura: "1.0 m",
        peso: "6.4 kg",
        gruposHuevo: ["Grass"],
        genero: new Genero(),
        habilidades: ["Chlorophyll", "Gluttony"],
        stats:new Stats(7,9,5,9,5,6),
        velocidades:new Velocidades(2,null,null,null,null),
        atributos:new Atributos(-2,0),
        skills:["Dec +5","Per +3","Ste +7","Sur +5"],
        caracteristicas:["Size - Medium"],
        evolution: "Victreebel - Leafstone"
    },
    {
        dexNum: 71,
        nombre: "Victreebel",
        tipo1: "Grass",
        tipo2: "Poison",
        especie: "Flycatcher Pokémon",
        altura: "1.7 m",
        peso: "15.5 kg",
        gruposHuevo: ["Grass"],
        genero: new Genero(),
        habilidades: ["Chlorophyll", "Gluttony"],
        stats:new Stats(8,11,7,10,7,7),
        velocidades:new Velocidades(2,null,null,null,null),
        atributos:new Atributos(-1,3),
        skills:["Dec +7","Per +4","Ste +8","Sur +6"],
        caracteristicas:["Size - Medium"],
        evolution: ""
    },
    {
        dexNum: 72,
        nombre: "Tentacool",
        tipo1: "Water",
        tipo2: "Poison",
        especie: "Jellyfish Pokémon",
        altura: "0.9 m",
        peso: "45.5 kg",
        gruposHuevo: ["Water 3"],
        genero: new Genero(),
        habilidades: ["Clear Body", "Liquid Ooze", "Rain Dish"],
        stats:new Stats(4,4,4,5,10,7),
        velocidades:new Velocidades(null,null,null,3,null),
        atributos:new Atributos(-2,-2),
        skills:["Ath +4","Per +4","Sur +5"],
        caracteristicas:["Size - Small","Waterbreathing","Hatchrate - Med"],
        evolution: "Tentacruel - 6"
    },
    {
        dexNum: 73,
        nombre: "Tentacruel",
        tipo1: "Water",
        tipo2: "Poison",
        especie: "Jellyfish Pokémon",
        altura: "1.6 m",
        peso: "55.0 kg",
        gruposHuevo: ["Water 3"],
        genero: new Genero(),
        habilidades: ["Clear Body", "Liquid Ooze", "Rain Dish"],
        stats:new Stats(8,7,7,8,12,10),
        velocidades:new Velocidades(null,null,null,2,null),
        atributos:new Atributos(1,2),
        skills:["Ath +7","Per +7","Sur +8"],
        caracteristicas:["Size - Medium","Waterbreathing"],
        evolution: ""
    },
    {
        dexNum: 74,
        nombre: "Geodude",
        tipo1: "Rock",
        tipo2: "Ground",
        especie: "Rock Pokémon",
        altura: "0.4 m",
        peso: "20.0 kg",
        gruposHuevo: ["Mineral"],
        genero: new Genero(),
        habilidades: ["Rock Head", "Sturdy", "Sand Veil"],
        stats:new Stats(4,8,10,3,3,2),
        velocidades:new Velocidades(4,null,1,null,null),
        atributos:new Atributos(-1,2),
        skills:["Athl +5","Dec +4","Ste +5"],
        caracteristicas:["Size - Medium","Earthmaker","Hatchrate - Short"],
        evolution: "Graveler - 5"
    },
    {
        dexNum: 75,
        nombre: "Graveler",
        tipo1: "Rock",
        tipo2: "Ground",
        especie: "Rock Pokémon",
        altura: "1.0 m",
        peso: "105.0 kg",
        gruposHuevo: ["Mineral"],
        genero: new Genero(),
        habilidades: ["Rock Head", "Sturdy", "Sand Veil"],
        stats:new Stats(6,10,12,5,5,4),
        velocidades:new Velocidades(4,null,null,null,0),
        atributos:new Atributos(-1,4),
        skills:["Athl +8","Dec +5","Ste +5"],
        caracteristicas:["Size - Medium","Earthmaker"],
        evolution: "Golem - ?"
    },
    {
        dexNum: 76,
        nombre: "Golem",
        tipo1: "Rock",
        tipo2: "Ground",
        especie: "Megaton Pokémon",
        altura: "1.4 m",
        peso: "300.0 kg",
        gruposHuevo: ["Mineral"],
        genero: new Genero(),
        habilidades: ["Rock Head", "Sturdy", "Sand Veil"],
        stats:new Stats(8,12,13,6,7,5),
        velocidades:new Velocidades(4,null,null,null,null),
        atributos:new Atributos(-1,5),
        skills:["Athl +10","Dec +5","Ste +5"],
        caracteristicas:["Size - Medium","Earthmaker"],
        evolution: ""
    },
    {
        dexNum: 77,
        nombre: "Ponyta",
        tipo1: "Fire",
        tipo2: "",
        especie: "Fire Horse Pokémon",
        altura: "1.0 m",
        peso: "30.0 kg",
        gruposHuevo: ["Field"],
        genero: new Genero(),
        habilidades: ["Run Away", "Flash Fire", "Flame Body"],
        stats:new Stats(5,9,6,7,7,9),
        velocidades:new Velocidades(6,null,null,null,null),
        atributos:new Atributos(0,1),
        skills:["Athl +6","End +6","Per +4"],
        caracteristicas:["Size - Medium","Mountable","Firestarter","Warm","Luminous","Hatchrate - Med"],
        evolution: "Rapidash - 8"
    },
    {
        dexNum: 78,
        nombre: "Rapidash",
        tipo1: "Fire",
        tipo2: "",
        especie: "Fire Horse Pokémon",
        altura: "1.7 m",
        peso: "95.0 kg",
        gruposHuevo: ["Field"],
        genero: new Genero(),
        habilidades: ["Run Away", "Flash Fire", "Flame Body"],
        stats:new Stats(7,10,7,8,8,11),
        velocidades:new Velocidades(7,null,null,null,null),
        atributos:new Atributos(1,2),
        skills:["Athl +10","End +8","Per +6"],
        caracteristicas:["Size - Medium","Mountable","Firestarter","Warm","Luminous"],
        evolution: ""
    },
    {
        dexNum: 79,
        nombre: "Slowpoke",
        tipo1: "Water",
        tipo2: "Psychic",
        especie: "Dopey Pokémon",
        altura: "1.2 m",
        peso: "36.0 kg",
        gruposHuevo: ["Monster", "Water 1"],
        genero: new Genero(),
        habilidades: ["Oblivious", "Own Tempo", "Regenerator"],
        stats:new Stats(9,7,7,4,4,2),
        velocidades:new Velocidades(2,null,null,2,null),
        atributos:new Atributos(0,-1),
        skills:["Psy +5"],
        caracteristicas:["Size - Medium","Hatchrate - Med"],
        evolution: "Slowbro - 7"
    },
    {
        dexNum: 80,
        nombre: "Slowbro",
        tipo1: "Water",
        tipo2: "Psychic",
        especie: "Hermit Crab Pokémon",
        altura: "1.6 m",
        peso: "78.5 kg",
        gruposHuevo: ["Monster", "Water 1"],
        genero: new Genero(),
        habilidades: ["Oblivious", "Own Tempo", "Regenerator"],
        stats:new Stats(10,8,11,10,8,3),
        velocidades:new Velocidades(4,null,null,4,null),
        atributos:new Atributos(2,0),
        skills:["Psy +9"],
        caracteristicas:["Size - Medium"],
        evolution: "Slowking - King's Rock"
    },
    {
        dexNum: 81,
        nombre: "Magnemite",
        tipo1: "Electric",
        tipo2: "Steel",
        especie: "Magnet Pokémon",
        altura: "0.3 m",
        peso: "6.0 kg",
        gruposHuevo: ["Mineral"],
        genero: new Genero(0,0),
        habilidades: ["Magnet Pull", "Sturdy", "Analytic"],
        stats:new Stats(3,4,7,10,6,5),
        velocidades:new Velocidades(3,null,null,null,null),
        atributos:new Atributos(0,-2),
        skills:["Comp +4","Mec +4","Per +4"],
        caracteristicas:["Size - Small","Magnetic","Levitator","Generator","Hatchrate - Med"],
        evolution: "Magneton - 6"
    },
    {
        dexNum: 82,
        nombre: "Magneton",
        tipo1: "Electric",
        tipo2: "Steel",
        especie: "Magnet Pokémon",
        altura: "1.0 m",
        peso: "60.0 kg",
        gruposHuevo: ["Mineral"],
        genero: new Genero(0,0),
        habilidades: ["Magnet Pull", "Sturdy", "Analytic"],
        stats:new Stats(5,6,10,12,7,7),
        velocidades:new Velocidades(3,null,null,null,null),
        atributos:new Atributos(2,0),
        skills:["Comp +7","Mec +6","Per +6"],
        caracteristicas:["Size - Medium","Magnetic","Levitator","Generator"],
        evolution: "Magnezone - Magnetic Field"
    },
    {
        dexNum: 83,
        nombre: "Farfetch'd",
        tipo1: "Normal",
        tipo2: "Flying",
        especie: "Wild Duck Pokémon",
        altura: "0.8 m",
        peso: "15.0 kg",
        gruposHuevo: ["Flying", "Field"],
        genero: new Genero(),
        habilidades: ["Keen Eye", "Inner Focus", "Defiant"],
        stats:new Stats(6,9,6,6,7,6),
        velocidades:new Velocidades(0,3,null,null,null),
        atributos:new Atributos(2,-1),
        skills:["Acro +8","Athl +6","End +6","PkCom +5","Sur +5"],
        caracteristicas:["Size - Small","Weapon Use","Hatchrate - Med"],
        evolution: ""
    },
    {
        dexNum: 84,
        nombre: "Doduo",
        tipo1: "Normal",
        tipo2: "Flying",
        especie: "Twin Bird Pokémon",
        altura: "1.4 m",
        peso: "39.2 kg",
        gruposHuevo: ["Flying"],
        genero: new Genero(),
        habilidades: ["Run Away", "Early Bird", "Tangled Feet"],
        stats:new Stats(4,9,5,4,4,8),
        velocidades:new Velocidades(3,null,null,null,null),
        atributos:new Atributos(-2,0),
        skills:["Acro +4","Athl +6","End +5","Per +5","Sur +4"],
        caracteristicas:["Size - Medium","Mountable","Hatchrate - Med"],
        evolution: "Dodrio - 6"
    },
    {
        dexNum: 85,
        nombre: "Dodrio",
        tipo1: "Normal",
        tipo2: "Flying",
        especie: "Triple Bird Pokémon",
        altura: "1.8 m",
        peso: "85.2 kg",
        gruposHuevo: ["Flying"],
        genero: new Genero(),
        habilidades: ["Run Away", "Early Bird", "Tangled Feet"],
        stats:new Stats(6,11,7,6,6,11),
        velocidades:new Velocidades(3,null,null,null,null),
        atributos:new Atributos(-1,2),
        skills:["Acro +7","Athl +9","End +7","Per +8","Sur +6"],
        caracteristicas:["Size - Medium","Mountable"],
        evolution: ""
    },
    {
        dexNum: 86,
        nombre: "Seel",
        tipo1: "Water",
        tipo2: "",
        especie: "Sea Lion Pokémon",
        altura: "1.1 m",
        peso: "90.0 kg",
        gruposHuevo: ["Water 1", "Field"],
        genero: new Genero(),
        habilidades: ["Thick Fat", "Hydration", "Ice Body"],
        stats:new Stats(7,5,6,5,7,5),
        velocidades:new Velocidades(1,null,null,4,null),
        atributos:new Atributos(-1,0),
        skills:["Per +4","Sur +4"],
        caracteristicas:["Size - Medium","Hatchrate - Med"],
        evolution: "Dewgong - 7"
    },
    {
        dexNum: 87,
        nombre: "Dewgong",
        tipo1: "Water",
        tipo2: "Ice",
        especie: "Sea Lion Pokémon",
        altura: "1.7 m",
        peso: "120.0 kg",
        gruposHuevo: ["Water 1", "Field"],
        genero: new Genero(),
        habilidades: ["Thick Fat", "Hydration", "Ice Body"],
        stats:new Stats(9,7,8,7,10,7),
        velocidades:new Velocidades(0,null,null,4,null),
        atributos:new Atributos(0,2),
        skills:["Per +7","Sur +7"],
        caracteristicas:["Size - Medium","Mountable"],
        evolution: ""
    },
    {
        dexNum: 88,
        nombre: "Grimer",
        tipo1: "Poison",
        tipo2: "",
        especie: "Sludge Pokémon",
        altura: "0.9 m",
        peso: "30.0 kg",
        gruposHuevo: ["Amorphous"],
        genero: new Genero(),
        habilidades: ["Stench", "Sticky Hold", "Poison Touch"],
        stats:new Stats(8,8,5,4,5,3),
        velocidades:new Velocidades(3,null,null,null,null),
        atributos:new Atributos(-2,0),
        skills:[],
        caracteristicas:["Size - Small","Amorphous","Hatchrate - Med"],
        evolution: "Muk - 7"
    },
    {
        dexNum: 89,
        nombre: "Muk",
        tipo1: "Poison",
        tipo2: "",
        especie: "Sludge Pokémon",
        altura: "1.2 m",
        peso: "30.0 kg",
        gruposHuevo: ["Amorphous"],
        genero: new Genero(),
        habilidades: ["Stench", "Sticky Hold", "Poison Touch"],
        stats:new Stats(11,11,8,7,10,5),
        velocidades:new Velocidades(3,null,null,null,null),
        atributos:new Atributos(-2,3),
        skills:["Athl +7"],
        caracteristicas:["Size - Medium","Amorphous"],
        evolution: ""
    },
    {
        dexNum: 90,
        nombre: "Shellder",
        tipo1: "Water",
        tipo2: "",
        especie: "Bivalve Pokémon",
        altura: "0.3 m",
        peso: "4.0 kg",
        gruposHuevo: ["Water 3"],
        genero: new Genero(),
        habilidades: ["Shell Armor", "Skill Link", "Overcoat"],
        stats:new Stats(3,7,10,5,3,4),
        velocidades:new Velocidades(null,null,null,4,null),
        atributos:new Atributos(-2,-2),
        skills:["Per +6","Sur +4"],
        caracteristicas:["Size - Small","Waterbreathing","Wellspring","Hatchrate - Med"],
        evolution: "Cloyster - Waterstone"
    },
    {
        dexNum: 91,
        nombre: "Cloyster",
        tipo1: "Water",
        tipo2: "Ice",
        especie: "Bivalve Pokémon",
        altura: "1.5 m",
        peso: "132.5 kg",
        gruposHuevo: ["Water 3"],
        genero: new Genero(),
        habilidades: ["Shell Armor", "Skill Link", "Overcoat"],
        stats:new Stats(5,10,18,9,5,7),
        velocidades:new Velocidades(null,null,null,4,null),
        atributos:new Atributos(0,2),
        skills:["Per +8","Sur +6"],
        caracteristicas:["Size - Medium","Waterbreathing","Wellspring"],
        evolution: ""
    },
    {
        dexNum: 92,
        nombre: "Gastly",
        tipo1: "Ghost",
        tipo2: "Poison",
        especie: "Gas Pokémon",
        altura: "1.3 m",
        peso: "0.1 kg",
        gruposHuevo: ["Amorphous"],
        genero: new Genero(),
        habilidades: ["Levitate"],
        stats:new Stats(3,4,3,10,4,8),
        velocidades:new Velocidades(2,0,null,null,null),
        atributos:new Atributos(1,null),
        skills:["Dec +4","Intim +4","Myst +6","Ste +4"],
        caracteristicas:["Size - Medium","Incorporeal","Invisibility","Hatchrate - Med"],
        evolution: "Haunter - 5"
    },
    {
        dexNum: 93,
        nombre: "Haunter",
        tipo1: "Ghost",
        tipo2: "Poison",
        especie: "Gas Pokémon",
        altura: "1.6 m",
        peso: "0.1 kg",
        gruposHuevo: ["Amorphous"],
        genero: new Genero(),
        habilidades: ["Levitate"],
        stats:new Stats(5,5,5,12,6,10),
        velocidades:new Velocidades(1,0,null,null,null),
        atributos:new Atributos(1,-1),
        skills:["Dec +7","Intim +7","Myst +8","Ste +5"],
        caracteristicas:["Size - Medium","Incorporeal","Invisibility"],
        evolution: "Gengar - ?"
    },
    {
        dexNum: 94,
        nombre: "Gengar",
        tipo1: "Ghost",
        tipo2: "Poison",
        especie: "Shadow Pokémon",
        altura: "1.5 m",
        peso: "40.5 kg",
        gruposHuevo: ["Amorphous"],
        genero: new Genero(),
        habilidades: ["Cursed Body"],
        stats:new Stats(6,7,6,13,8,11),
        velocidades:new Velocidades(2,2,null,null,null),
        atributos:new Atributos(2,1),
        skills:["Dec +8","Intim +8","Myst +12","Ste +8"],
        caracteristicas:["Size - Medium","Incorporeal","Invisibility"],
        evolution: ""
    },
    {
        dexNum: 95,
        nombre: "Onix",
        tipo1: "Rock",
        tipo2: "Ground",
        especie: "Rock Snake Pokémon",
        altura: "8.8 m",
        peso: "210.0 kg",
        gruposHuevo: ["Mineral"],
        genero: new Genero(),
        habilidades: ["Rock Head", "Sturdy", "Weak Armor"],
        stats:new Stats(4,5,16,3,5,7),
        velocidades:new Velocidades(3,null,1,null,null),
        atributos:new Atributos(-1,4),
        skills:["Athl +8","End +7","Intim +6"],
        caracteristicas:["Size - Large","Mountable","Hatchrate - Long"],
        evolution: "Steelix - Iron Coat"
    },
    {
        dexNum: 96,
        nombre: "Drowzee",
        tipo1: "Psychic",
        tipo2: "",
        especie: "Hypnosis Pokémon",
        altura: "1.0 m",
        peso: "32.4 kg",
        gruposHuevo: ["Human-Like"],
        genero: new Genero(),
        habilidades: ["Insomnia", "Forewarn", "Inner Focus"],
        stats:new Stats(6,5,5,4,9,4),
        velocidades:new Velocidades(3,null,null,null,null),
        atributos:new Atributos(1,-1),
        skills:["Ins +4","Per +4","Psy +6"],
        caracteristicas:["Size - Medium","Telepathic","Telekinetic","Hatchrate - Med"],
        evolution: "Hypno - 5"
    },
    {
        dexNum: 97,
        nombre: "Hypno",
        tipo1: "Psychic",
        tipo2: "",
        especie: "Hypnosis Pokémon",
        altura: "1.6 m",
        peso: "75.6 kg",
        gruposHuevo: ["Human-Like"],
        genero: new Genero(),
        habilidades: ["Insomnia", "Forewarn", "Inner Focus"],
        stats:new Stats(9,7,7,7,12,7),
        velocidades:new Velocidades(3,null,null,null,null),
        atributos:new Atributos(4,1),
        skills:["Ins +4","Per +4","Psy +6"],
        caracteristicas:["Size - Medium","Telepathic","Telekinetic"],
        evolution: ""
    },
    {
        dexNum: 98,
        nombre: "Krabby",
        tipo1: "Water",
        tipo2: "",
        especie: "River Crab Pokémon",
        altura: "0.4 m",
        peso: "6.5 kg",
        gruposHuevo: ["Water 3"],
        genero: new Genero(),
        habilidades: ["Hyper Cutter", "Shell Armor", "Sheer Force"],
        stats:new Stats(3,11,9,3,3,5),
        velocidades:new Velocidades(3,null,null,2,null),
        atributos:new Atributos(-2,-1),
        skills:["Intim +3","Per +4","Sur +4"],
        caracteristicas:["Size - Small","Waterbreathing","Hatchrate - Med"],
        evolution: "Kingler - 5"
    },
    {
        dexNum: 99,
        nombre: "Kingler",
        tipo1: "Water",
        tipo2: "",
        especie: "Pincer Pokémon",
        altura: "1.3 m",
        peso: "60.0 kg",
        gruposHuevo: ["Water 3"],
        genero: new Genero(),
        habilidades: ["Hyper Cutter", "Shell Armor", "Sheer Force"],
        stats:new Stats(6,13,12,5,5,8),
        velocidades:new Velocidades(2,null,null,1,null),
        atributos:new Atributos(-1,2),
        skills:["Athl +4","Intim +8","Per +6","Sur +5"],
        caracteristicas:["Size - Medium","Waterbreathing"],
        evolution: ""
    },
    {
        dexNum: 100,
        nombre: "Voltorb",
        tipo1: "Electric",
        tipo2: "",
        especie: "Ball Pokémon",
        altura: "0.5 m",
        peso: "10.4 kg",
        gruposHuevo: ["Mineral"],
        genero: new Genero(0,0),
        habilidades: ["Soundproof", "Static", "Aftermath"],
        stats:new Stats(4,3,5,6,6,10),
        velocidades:new Velocidades(0,null,null,null,null),
        atributos:new Atributos(1,-2),
        skills:["Comp +6","Intim +4","Mec +2","Per +4"],
        caracteristicas:["Size - Small","Generator","Levitator","Volatile","Hatchrate - Med"],
        evolution: "Electrode - 6"
    },
    {
        dexNum: 101,
        nombre: "Electrode",
        tipo1: "Electric",
        tipo2: "",
        especie: "Ball Pokémon",
        altura: "1.2 m",
        peso: "66.6 kg",
        gruposHuevo: ["Mineral"],
        genero: new Genero(0,0),
        habilidades: ["Soundproof", "Static", "Aftermath"],
        stats:new Stats(6,5,7,8,8,15),
        velocidades:new Velocidades(0,null,null,null,null),
        atributos:new Atributos(3,0),
        skills:["Comp +9","Intim +8","Mec +5","Per +6"],
        caracteristicas:["Size - Medium","Generator","Levitator","Volatile"],
        evolution: ""
    },
    {
        dexNum: 102,
        nombre: "Exeggcute",
        tipo1: "Grass",
        tipo2: "Psychic",
        especie: "Egg Pokémon",
        altura: "0.4 m",
        peso: "2.5 kg",
        gruposHuevo: ["Grass"],
        genero: new Genero(),
        habilidades: ["Chlorophyll", "Harvest"],
        stats:new Stats(6,4,8,6,5,4),
        velocidades:new Velocidades(3,null,null,null,null),
        atributos:new Atributos(1,-2),
        skills:["Dec +3","Ins +4","Per +6","Psy +7"],
        caracteristicas:["Size - Small","Telekinetic","Hatchrate - Med"],
        evolution: "Exeggutor - Leafstone"
    },
    {
        dexNum: 103,
        nombre: "Exeggutor",
        tipo1: "Grass",
        tipo2: "Psychic",
        especie: "Coconut Pokémon",
        altura: "2.0 m",
        peso: "120.0 kg",
        gruposHuevo: ["Grass"],
        genero: new Genero(),
        habilidades: ["Chlorophyll", "Harvest"],
        stats:new Stats(10,10,9,13,8,6),
        velocidades:new Velocidades(3,null,null,null,null),
        atributos:new Atributos(1,3),
        skills:["Athl +5","Dec +6","Ins +6","Per +7","Psy +10"],
        caracteristicas:["Size - Medium","Telekinetic"],
        evolution: ""
    },
    {
        dexNum: 104,
        nombre: "Cubone",
        tipo1: "Ground",
        tipo2: "",
        especie: "Lonely Pokémon",
        altura: "0.4 m",
        peso: "6.5 kg",
        gruposHuevo: ["Monster"],
        genero: new Genero(),
        habilidades: ["Rock Head", "Lightning Rod", "Battle Armor"],
        stats:new Stats(5,5,10,4,5,4),
        velocidades:new Velocidades(3,null,0,null,null),
        atributos:new Atributos(0,1),
        skills:["Acro +4","Athl +4","End +5","Ins +3","Per +3","Sur +4"],
        caracteristicas:["Size - Small","Hatchrate - Med"],
        evolution: "Marowak - 5"
    },
    {
        dexNum: 105,
        nombre: "Marowak",
        tipo1: "Ground",
        tipo2: "",
        especie: "Bone Keeper Pokémon",
        altura: "1.0 m",
        peso: "45.0 kg",
        gruposHuevo: ["Monster"],
        genero: new Genero(),
        habilidades: ["Rock Head", "Lightning Rod", "Battle Armor"],
        stats:new Stats(6,8,11,5,8,5),
        velocidades:new Velocidades(4,null,0,null,null),
        atributos:new Atributos(0,3),
        skills:["Acro +8","Athl +8","End +9","Ins +7","Per +6","Sur +5"],
        caracteristicas:["Size - Medium"],
        evolution: ""
    },
    {
        dexNum: 106,
        nombre: "Hitmonlee",
        tipo1: "Fighting",
        tipo2: "",
        especie: "Kicking Pokémon",
        altura: "1.5 m",
        peso: "49.8 kg",
        gruposHuevo: ["Human-Like"],
        genero: new Genero(100,0),
        habilidades: ["Limber", "Reckless", "Unburden"],
        stats:new Stats(5,12,5,4,11,9),
        velocidades:new Velocidades(3,null,null,null,null),
        atributos:new Atributos(0,3),
        skills:["Acro +11","End +8","PkCom +7","Train +7"],
        caracteristicas:["Size - Medium"],
        evolution: ""
    },
    {
        dexNum: 107,
        nombre: "Hitmonchan",
        tipo1: "Fighting",
        tipo2: "",
        especie: "Punching Pokémon",
        altura: "1.4 m",
        peso: "50.2 kg",
        gruposHuevo: ["Human-Like"],
        genero: new Genero(100,0),
        habilidades: ["Keen Eye", "Iron Fist", "Inner Focus"],
        stats:new Stats(5,11,8,4,11,8),
        velocidades:new Velocidades(2,null,null,null,null),
        atributos:new Atributos(1,3),
        skills:["Athl +10","End +8","PkCom +8","Train +8"],
        caracteristicas:["Size - Medium"],
        evolution: ""
    },
    {
        dexNum: 108,
        nombre: "Lickitung",
        tipo1: "Normal",
        tipo2: "",
        especie: "Licking Pokémon",
        altura: "1.2 m",
        peso: "65.5 kg",
        gruposHuevo: ["Monster"],
        genero: new Genero(),
        habilidades: ["Own Tempo", "Oblivious", "Cloud Nine"],
        stats:new Stats(9,6,8,6,8,3),
        velocidades:new Velocidades(4,null,null,null,null),
        atributos:new Atributos(-1,1),
        skills:["Athl +3","Intim +5","Per +4"],
        caracteristicas:["Size - Medium","Hatchrate - Med"],
        evolution: "Lickilicky - Rollout"
    },
    {
        dexNum: 109,
        nombre: "Koffing",
        tipo1: "Poison",
        tipo2: "",
        especie: "Poison Gas Pokémon",
        altura: "0.6 m",
        peso: "1.0 kg",
        gruposHuevo: ["Amorphous"],
        genero: new Genero(),
        habilidades: ["Levitate"],
        stats:new Stats(4,7,10,6,5,4),
        velocidades:new Velocidades(2,null,null,null,null),
        atributos:new Atributos(-2,-1),
        skills:["Intim +7"],
        caracteristicas:["Size - Small","Levitator","Volatile","Hatchrate - Med"],
        evolution: "Weezing - 7"
    },
    {
        dexNum: 110,
        nombre: "Weezing",
        tipo1: "Poison",
        tipo2: "",
        especie: "Poison Gas Pokémon",
        altura: "1.2 m",
        peso: "9.5 kg",
        gruposHuevo: ["Amorphous"],
        genero: new Genero(),
        habilidades: ["Levitate"],
        stats:new Stats(7,9,12,9,7,6),
        velocidades:new Velocidades(2,null,null,null,null),
        atributos:new Atributos(-1,0),
        skills:["Intim +10"],
        caracteristicas:["Size - Medium","Levitator","Volatile"],
        evolution: ""
    },
    {
        dexNum: 111,
        nombre: "Rhyhorn",
        tipo1: "Ground",
        tipo2: "Rock",
        especie: "Spikes Pokémon",
        altura: "1.0 m",
        peso: "115.0 kg",
        gruposHuevo: ["Monster", "Field"],
        genero: new Genero(),
        habilidades: ["Lightning Rod", "Rock Head", "Reckless"],
        stats:new Stats(8,9,10,3,3,3),
        velocidades:new Velocidades(6,null,null,null,null),
        atributos:new Atributos(-1,3),
        skills:["Athl +6","End +6","Intim +4"],
        caracteristicas:["Size - Medium","Mountable","Hatchrate - Med"],
        evolution: "Rhydon - 8"
    },
    {
        dexNum: 112,
        nombre: "Rhydon",
        tipo1: "Ground",
        tipo2: "Rock",
        especie: "Drill Pokémon",
        altura: "1.9 m",
        peso: "120.0 kg",
        gruposHuevo: ["Monster", "Field"],
        genero: new Genero(),
        habilidades: ["Lightning Rod", "Rock Head", "Reckless"],
        stats:new Stats(11,13,12,5,5,4),
        velocidades:new Velocidades(4,null,1,null,null),
        atributos:new Atributos(1,4),
        skills:["Athl +8","End +6","Intim +6","Per +6"],
        caracteristicas:["Size - Medium","Earthmaker"],
        evolution: "Rhyperior - Protector"
    },
    {
        dexNum: 113,
        nombre: "Chansey",
        tipo1: "Normal",
        tipo2: "",
        especie: "Egg Pokémon",
        altura: "1.1 m",
        peso: "34.6 kg",
        gruposHuevo: ["Fairy"],
        genero: new Genero(0,100),
        habilidades: ["Natural Cure", "Serene Grace", "Healer"],
        stats:new Stats(25,1,1,4,11,5),
        velocidades:new Velocidades(4,null,null,null,null),
        atributos:new Atributos(2,-1),
        skills:["F.Aid +8","Ins +6","Poke +6"],
        caracteristicas:["Size - Medium"],
        evolution: "Blissey - Max Loyalty"
    },
    {
        dexNum: 114,
        nombre: "Tangela",
        tipo1: "Grass",
        tipo2: "",
        especie: "Vine Pokémon",
        altura: "1.0 m",
        peso: "35.0 kg",
        gruposHuevo: ["Grass"],
        genero: new Genero(),
        habilidades: ["Chlorophyll", "Leaf Guard", "Regenerator"],
        stats:new Stats(7,6,12,10,4,6),
        velocidades:new Velocidades(3,null,null,null,null),
        atributos:new Atributos(1,0),
        skills:["Athl +4","Dec +6","Per +6","Sur +7"],
        caracteristicas:["Size - Small","Reach 1","Hatchrate - Med"],
        evolution: "Tangrowth - Ancient Power"
    },
    {
        dexNum: 115,
        nombre: "Kangaskhan",
        tipo1: "Normal",
        tipo2: "",
        especie: "Parent Pokémon",
        altura: "2.2 m",
        peso: "80.0 kg",
        gruposHuevo: ["Monster"],
        genero: new Genero(0,100),
        habilidades: ["Early Bird", "Scrappy", "Inner Focus"],
        stats:new Stats(11,10,8,4,8,9),
        velocidades:new Velocidades(2,null,null,null,null),
        atributos:new Atributos(-1,4),
        skills:["Athl +9","End +5","Intim +6","Per +6","Sur +6"],
        caracteristicas:["Size - Large", "Hatchrate - Med"],
        evolution: ""
    },
    {
        dexNum: 116,
        nombre: "Horsea",
        tipo1: "Water",
        tipo2: "",
        especie: "Dragon Pokémon",
        altura: "0.4 m",
        peso: "8.0 kg",
        gruposHuevo: ["Water 1", "Dragon"],
        genero: new Genero(),
        habilidades: ["Swift Swim", "Sniper", "Damp"],
        stats:new Stats(3,4,7,7,3,6),
        velocidades:new Velocidades(null,null,null,3,null),
        atributos:new Atributos(0,-1),
        skills:["Acro +6","Per +4","Ste +4","Sur +4"],
        caracteristicas:["Size - Small","Waterbreathing","Wellspring","Hatchrate - Med"],
        evolution: "Seadra - 6"
    },
    {
        dexNum: 117,
        nombre: "Seadra",
        tipo1: "Water",
        tipo2: "",
        especie: "Dragon Pokémon",
        altura: "1.2 m",
        peso: "25.0 kg",
        gruposHuevo: ["Water 1", "Dragon"],
        genero: new Genero(),
        habilidades: ["Poison Point", "Sniper", "Damp"],
        stats:new Stats(6,7,10,10,5,9),
        velocidades:new Velocidades(null,null,null,4,null),
        atributos:new Atributos(1,2),
        skills:["Acro +9","Per +7","Ste +6","Sur +6"],
        caracteristicas:["Size - Medium","Waterbreathing","Wellspring"],
        evolution: "Kingdra - Dragon Scale"
    },
    {
        dexNum: 118,
        nombre: "Goldeen",
        tipo1: "Water",
        tipo2: "",
        especie: "Goldfish Pokémon",
        altura: "0.6 m",
        peso: "15.0 kg",
        gruposHuevo: ["Water 2"],
        genero: new Genero(),
        habilidades: ["Swift Swim", "Water Veil", "Lightning Rod"],
        stats:new Stats(5,7,6,4,5,6),
        velocidades:new Velocidades(null,null,null,4,null),
        atributos:new Atributos(-1,-1),
        skills:["Athl +6","End +6","Per +4"],
        caracteristicas:["Size - Small","Waterbreathing","Hatchrate - Med"],
        evolution: "Seaking - 6"
    },
    {
        dexNum: 119,
        nombre: "Seaking",
        tipo1: "Water",
        tipo2: "",
        especie: "Goldfish Pokémon",
        altura: "1.3 m",
        peso: "39.0 kg",
        gruposHuevo: ["Water 2"],
        genero: new Genero(),
        habilidades: ["Swift Swim", "Water Veil", "Lightning Rod"],
        stats:new Stats(8,9,7,7,8,7),
        velocidades:new Velocidades(null,null,null,5,null),
        atributos:new Atributos(-1,3),
        skills:["Athl +9","End +7","Per +6"],
        caracteristicas:["Size - Medium","Waterbreathing","Mountable"],
        evolution: ""
    },
    {
        dexNum: 120,
        nombre: "Staryu",
        tipo1: "Water",
        tipo2: "",
        especie: "Star Shape Pokémon",
        altura: "0.8 m",
        peso: "34.5 kg",
        gruposHuevo: ["Water 3"],
        genero: new Genero(0,0),
        habilidades: ["Illuminate", "Natural Cure", "Analytic"],
        stats:new Stats(3,5,6,7,6,9),
        velocidades:new Velocidades(-1,null,null,2,null),
        atributos:new Atributos(1,-2),
        skills:["Acro +5","Ins +3","Per +4","Sur +4"],
        caracteristicas:["Size - Small","Waterbreathing","Levitator","Telekinetic","Hatchrate - Med"],
        evolution: "Starmie - Waterstone"
    },
    {
        dexNum: 121,
        nombre: "Starmie",
        tipo1: "Water",
        tipo2: "Psychic",
        especie: "Mysterious Pokémon",
        altura: "1.1 m",
        peso: "80.0 kg",
        gruposHuevo: ["Water 3"],
        genero: new Genero(0,0),
        habilidades: ["Illuminate", "Natural Cure", "Analytic"],
        stats:new Stats(6,8,9,10,9,12),
        velocidades:new Velocidades(-2,null,null,0,null),
        atributos:new Atributos(3,1),
        skills:["Acro +8","Ins +5","Per +6","Psy +9","Sur +5"],
        caracteristicas:["Size - Small","Waterbreathing","Levitator","Telekinetic","Hatchrate - Med"],
        evolution: ""
    },
    {
        dexNum: 122,
        nombre: "Mr. Mime",
        tipo1: "Psychic",
        tipo2: "Fairy",
        especie: "Barrier Pokémon",
        altura: "1.3 m",
        peso: "54.5 kg",
        gruposHuevo: ["Human-Like"],
        genero: new Genero(),
        habilidades: ["Soundproof", "Filter", "Technician"],
        stats:new Stats(4,5,7,10,12,9),
        velocidades:new Velocidades(2,null,null,null,null),
        atributos:new Atributos(4,-1),
        skills:["Dec +5","Ins +8","Psy +11"],
        caracteristicas:["Size - Medium","Telepathic","Telekinetic"],
        evolution: ""
    },
    {
        dexNum: 123,
        nombre: "Scyther",
        tipo1: "Bug",
        tipo2: "Flying",
        especie: "Mantis Pokémon",
        altura: "1.5 m",
        peso: "56.0 kg",
        gruposHuevo: ["Bug"],
        genero: new Genero(),
        habilidades: ["Swarm", "Technician", "Steadfast"],
        stats:new Stats(7,11,8,6,8,11),
        velocidades:new Velocidades(1,1,null,null,null),
        atributos:new Atributos(0,2),
        skills:["Acro +8","Per +7","Sur +6"],
        caracteristicas:["Size - Medium", "Hatchrate - Long"],
        evolution: "Scizor - Metal Coat"
    },
    {
        dexNum: 124,
        nombre: "Jynx",
        tipo1: "Ice",
        tipo2: "Psychic",
        especie: "Human Shape Pokémon",
        altura: "1.4 m",
        peso: "40.6 kg",
        gruposHuevo: ["Human-Like"],
        genero: new Genero(0,100),
        habilidades: ["Oblivious", "Forewarn", "Dry Skin"],
        stats:new Stats(7,5,4,12,10,10),
        velocidades:new Velocidades(1,null,null,null,null),
        atributos:new Atributos(2,0),
        skills:["Ins +8","Psy +9","Sur +6"],
        caracteristicas:["Size - Medium","Telepathic","Telekinetic"],
        evolution: ""
    },
    {
        dexNum: 125,
        nombre: "Electabuzz",
        tipo1: "Electric",
        tipo2: "",
        especie: "Electric Pokémon",
        altura: "1.1 m",
        peso: "30.0 kg",
        gruposHuevo: ["Human-Like"],
        genero: new Genero(75.4,24.6),
        habilidades: ["Static", "Vital Spirit"],
        stats:new Stats(7,8,6,10,9,11),
        velocidades:new Velocidades(1,null,null,null,null),
        atributos:new Atributos(0,0),
        skills:["Acro +7","Athl +7"],
        caracteristicas:["Size - Medium","Generator"],
        evolution: "Electivire - Electirizer"
    },
    {
        dexNum: 126,
        nombre: "Magmar",
        tipo1: "Fire",
        tipo2: "",
        especie: "Spitfire Pokémon",
        altura: "1.3 m",
        peso: "44.5 kg",
        gruposHuevo: ["Human-Like"],
        genero: new Genero(75.4,24.6),
        habilidades: ["Flame Body", "Vital Spirit"],
        stats:new Stats(7,10,6,10,9,9),
        velocidades:new Velocidades(2,null,null,null,null),
        atributos:new Atributos(0,0),
        skills:["Acro +7","Athl +7"],
        caracteristicas:["Size - Medium","Firestarter","Luminous","Warm"],
        evolution: "Magmortar - Magmarizer"
    },
    {
        dexNum: 127,
        nombre: "Pinsir",
        tipo1: "Bug",
        tipo2: "",
        especie: "Stag Beetle Pokémon",
        altura: "1.5 m",
        peso: "55.0 kg",
        gruposHuevo: ["Bug"],
        genero: new Genero(),
        habilidades: ["Hyper Cutter", "Mold Breaker", "Moxie"],
        stats:new Stats(7,13,10,6,7,9),
        velocidades:new Velocidades(2,null,0,null,1),
        atributos:new Atributos(0,3),
        skills:["Athl +8","End +6","Intim +7"],
        caracteristicas:["Size - Medium","Hatchrate - Long"],
        evolution: ""
    },
    {
        dexNum: 128,
        nombre: "Tauros",
        tipo1: "Normal",
        tipo2: "",
        especie: "Wild Bull Pokémon",
        altura: "1.4 m",
        peso: "88.4 kg",
        gruposHuevo: ["Field"],
        genero: new Genero(),
        habilidades: ["Intimidate", "Anger Point", "Sheer Force"],
        stats:new Stats(,,,,,),
        velocidades:new Velocidades(null,null,null,null,null),
        atributos:new Atributos(,),
        skills:[],
        caracteristicas:[],
        evolution: ""
    },
    {
        dexNum: 129,
        nombre: "Magikarp",
        tipo1: "Water",
        tipo2: "",
        especie: "Fish Pokémon",
        altura: "0.9 m",
        peso: "10.0 kg",
        gruposHuevo: ["Water 2", "Dragon"],
        genero: new Genero(),
        habilidades: ["Swift Swim", "Rattled"],
        stats:new Stats(,,,,,),
        velocidades:new Velocidades(null,null,null,null,null),
        atributos:new Atributos(,),
        skills:[],
        caracteristicas:[],
        evolution: "Gyarados"
    },
    {
        dexNum: 130,
        nombre: "Gyarados",
        tipo1: "Water",
        tipo2: "Flying",
        especie: "Atrocious Pokémon",
        altura: "6.5 m",
        peso: "235.0 kg",
        gruposHuevo: ["Water 2", "Dragon"],
        genero: new Genero(),
        habilidades: ["Intimidate", "Moxie"],
        stats:new Stats(,,,,,),
        velocidades:new Velocidades(null,null,null,null,null),
        atributos:new Atributos(,),
        skills:[],
        caracteristicas:[],
        evolution: ""
    },
    {
        dexNum: 131,
        nombre: "Lapras",
        tipo1: "Water",
        tipo2: "Ice",
        especie: "Transport Pokémon",
        altura: "2.5 m",
        peso: "220.0 kg",
        gruposHuevo: ["Monster", "Water 1"],
        genero: new Genero(),
        habilidades: ["Water Absorb", "Shell Armor", "Hydration"],
        stats:new Stats(,,,,,),
        velocidades:new Velocidades(null,null,null,null,null),
        atributos:new Atributos(,),
        skills:[],
        caracteristicas:[],
        evolution: ""
    },
    {
        dexNum: 132,
        nombre: "Ditto",
        tipo1: "Normal",
        tipo2: "",
        especie: "Transform Pokémon",
        altura: "0.3 m",
        peso: "4.0 kg",
        gruposHuevo: ["Ditto"],
        genero: new Genero(),
        habilidades: ["Limber", "Imposter"],
        stats:new Stats(,,,,,),
        velocidades:new Velocidades(null,null,null,null,null),
        atributos:new Atributos(,),
        skills:[],
        caracteristicas:[],
        evolution: ""
    },
    {
        dexNum: 133,
        nombre: "Eevee",
        tipo1: "Normal",
        tipo2: "",
        especie: "Evolution Pokémon",
        altura: "0.3 m",
        peso: "6.5 kg",
        gruposHuevo: ["Field"],
        genero: new Genero(),
        habilidades: ["Run Away", "Adaptability", "Anticipation"],
        stats:new Stats(,,,,,),
        velocidades:new Velocidades(null,null,null,null,null),
        atributos:new Atributos(,),
        skills:[],
        caracteristicas:[],
        evolution: "Vaporeon, Jolteon, Flareon, Espeon, Umbreon, Leafeon, Glaceon, Sylveon"
    },
    {
        dexNum: 134,
        nombre: "Vaporeon",
        tipo1: "Water",
        tipo2: "",
        especie: "Bubble Jet Pokémon",
        altura: "1.0 m",
        peso: "29.0 kg",
        gruposHuevo: ["Field"],
        genero: new Genero(),
        habilidades: ["Water Absorb", "Hydration"],
        stats:new Stats(,,,,,),
        velocidades:new Velocidades(null,null,null,null,null),
        atributos:new Atributos(,),
        skills:[],
        caracteristicas:[],
        evolution: ""
    },
    {
        dexNum: 135,
        nombre: "Jolteon",
        tipo1: "Electric",
        tipo2: "",
        especie: "Lightning Pokémon",
        altura: "0.8 m",
        peso: "24.5 kg",
        gruposHuevo: ["Field"],
        genero: new Genero(),
        habilidades: ["Volt Absorb", "Quick Feet"],
        stats:new Stats(,,,,,),
        velocidades:new Velocidades(null,null,null,null,null),
        atributos:new Atributos(,),
        skills:[],
        caracteristicas:[],
        evolution: ""
    },
    {
        dexNum: 136,
        nombre: "Flareon",
        tipo1: "Fire",
        tipo2: "",
        especie: "Flame Pokémon",
        altura: "0.9 m",
        peso: "25.0 kg",
        gruposHuevo: ["Field"],
        habilidades: ["Flash Fire", "Guts"],
        stats:new Stats(,,,,,),
        velocidades:new Velocidades(null,null,null,null,null),
        atributos:new Atributos(,),
        skills:[],
        caracteristicas:[],
        evolution: ""
    },
    {
        dexNum: 137,
        nombre: "Porygon",
        tipo1: "Normal",
        tipo2: "",
        especie: "Virtual Pokémon",
        altura: "0.8 m",
        peso: "36.5 kg",
        gruposHuevo: ["Mineral"],
        genero: new Genero(),
        habilidades: ["Trace", "Download", "Analytic"],
        stats:new Stats(,,,,,),
        velocidades:new Velocidades(null,null,null,null,null),
        atributos:new Atributos(,),
        skills:[],
        caracteristicas:[],
        evolution: "Porygon2"
    },
    {
        dexNum: 138,
        nombre: "Omanyte",
        tipo1: "Rock",
        tipo2: "Water",
        especie: "Spiral Pokémon",
        altura: "0.4 m",
        peso: "7.5 kg",
        gruposHuevo: ["Water 1", "Water 3"],
        genero: new Genero(),
        habilidades: ["Swift Swim", "Shell Armor", "Weak Armor"],
        stats:new Stats(,,,,,),
        velocidades:new Velocidades(null,null,null,null,null),
        atributos:new Atributos(,),
        skills:[],
        caracteristicas:[],
        evolution: "Omastar"
    },
    {
        dexNum: 139,
        nombre: "Omastar",
        tipo1: "Rock",
        tipo2: "Water",
        especie: "Spiral Pokémon",
        altura: "1.0 m",
        peso: "35.0 kg",
        gruposHuevo: ["Water 1", "Water 3"],
        genero: new Genero(),
        habilidades: ["Swift Swim", "Shell Armor", "Weak Armor"],
        stats:new Stats(,,,,,),
        velocidades:new Velocidades(null,null,null,null,null),
        atributos:new Atributos(,),
        skills:[],
        caracteristicas:[],
        evolution: ""
    },
    {
        dexNum: 140,
        nombre: "Kabuto",
        tipo1: "Rock",
        tipo2: "Water",
        especie: "Shellfish Pokémon",
        altura: "0.5 m",
        peso: "11.5 kg",
        gruposHuevo: ["Water 1", "Water 3"],
        genero: new Genero(),
        habilidades: ["Swift Swim", "Battle Armor", "Weak Armor"],
        stats:new Stats(,,,,,),
        velocidades:new Velocidades(null,null,null,null,null),
        atributos:new Atributos(,),
        skills:[],
        caracteristicas:[],
        evolution: "Kabutops"
    },
    {
        dexNum: 141,
        nombre: "Kabutops",
        tipo1: "Rock",
        tipo2: "Water",
        especie: "Shellfish Pokémon",
        altura: "1.3 m",
        peso: "40.5 kg",
        gruposHuevo: ["Water 1", "Water 3"],
        genero: new Genero(),
        habilidades: ["Swift Swim", "Battle Armor", "Weak Armor"],
        stats:new Stats(,,,,,),
        velocidades:new Velocidades(null,null,null,null,null),
        atributos:new Atributos(,),
        skills:[],
        caracteristicas:[],
        evolution: ""
    },
    {
        dexNum: 142,
        nombre: "Aerodactyl",
        tipo1: "Rock",
        tipo2: "Flying",
        especie: "Fossil Pokémon",
        altura: "1.8 m",
        peso: "59.0 kg",
        gruposHuevo: ["Flying"],
        genero: new Genero(),
        habilidades: ["Rock Head", "Pressure", "Unnerve"],
        stats:new Stats(,,,,,),
        velocidades:new Velocidades(null,null,null,null,null),
        atributos:new Atributos(,),
        skills:[],
        caracteristicas:[],
        evolution: ""
    },
    {
        dexNum: 143,
        nombre: "Snorlax",
        tipo1: "Normal",
        tipo2: "",
        especie: "Sleeping Pokémon",
        altura: "2.1 m",
        peso: "460.0 kg",
        gruposHuevo: ["Monster"],
        genero: new Genero(),
        habilidades: ["Immunity", "Thick Fat", "Gluttony"],
        stats:new Stats(,,,,,),
        velocidades:new Velocidades(null,null,null,null,null),
        atributos:new Atributos(,),
        skills:[],
        caracteristicas:[],
        evolution: ""
    },
    {
        dexNum: 144,
        nombre: "Articuno",
        tipo1: "Ice",
        tipo2: "Flying",
        especie: "Freeze Pokémon",
        altura: "1.7 m",
        peso: "55.4 kg",
        gruposHuevo: ["Undiscovered"],
        genero: new Genero(),
        habilidades: ["Pressure", "Snow Cloak"],
        stats:new Stats(,,,,,),
        velocidades:new Velocidades(null,null,null,null,null),
        atributos:new Atributos(,),
        skills:[],
        caracteristicas:[],
        evolution: ""
    },
    {
        dexNum: 145,
        nombre: "Zapdos",
        tipo1: "Electric",
        tipo2: "Flying",
        especie: "Electric Pokémon",
        altura: "1.6 m",
        peso: "52.6 kg",
        gruposHuevo: ["Undiscovered"],
        genero: new Genero(),
        habilidades: ["Pressure", "Static"],
        stats:new Stats(,,,,,),
        velocidades:new Velocidades(null,null,null,null,null),
        atributos:new Atributos(,),
        skills:[],
        caracteristicas:[],
        evolution: ""
    },
    {
        dexNum: 146,
        nombre: "Moltres",
        tipo1: "Fire",
        tipo2: "Flying",
        especie: "Flame Pokémon",
        altura: "2.0 m",
        peso: "60.0 kg",
        gruposHuevo: ["Undiscovered"],
        genero: new Genero(),
        habilidades: ["Pressure", "Flame Body"],
        stats:new Stats(,,,,,),
        velocidades:new Velocidades(null,null,null,null,null),
        atributos:new Atributos(,),
        skills:[],
        caracteristicas:[],
        evolution: ""
    },
    {
        dexNum: 147,
        nombre: "Dratini",
        tipo1: "Dragon",
        tipo2: "",
        especie: "Dragon Pokémon",
        altura: "1.8 m",
        peso: "3.3 kg",
        gruposHuevo: ["Dragon", "Water 1"],
        genero: new Genero(),
        habilidades: ["Shed Skin", "Marvel Scale"],
        stats:new Stats(,,,,,),
        velocidades:new Velocidades(null,null,null,null,null),
        atributos:new Atributos(,),
        skills:[],
        caracteristicas:[],
        evolution: "Dragonair"
    },
    {
        dexNum: 148,
        nombre: "Dragonair",
        tipo1: "Dragon",
        tipo2: "",
        especie: "Dragon Pokémon",
        altura: "4.0 m",
        peso: "16.5 kg",
        gruposHuevo: ["Dragon", "Water 1"],
        genero: new Genero(),
        habilidades: ["Shed Skin", "Marvel Scale"],
        stats:new Stats(,,,,,),
        velocidades:new Velocidades(null,null,null,null,null),
        atributos:new Atributos(,),
        skills:[],
        caracteristicas:[],
        evolution: "Dragonite"
    },
    {
        dexNum: 149,
        nombre: "Dragonite",
        tipo1: "Dragon",
        tipo2: "Flying",
        especie: "Dragon Pokémon",
        altura: "2.2 m",
        peso: "210.0 kg",
        gruposHuevo: ["Dragon", "Water 1"],
        genero: new Genero(),
        habilidades: ["Inner Focus", "Multiscale"],
        stats:new Stats(,,,,,),
        velocidades:new Velocidades(null,null,null,null,null),
        atributos:new Atributos(,),
        skills:[],
        caracteristicas:[],
        evolution: ""
    },
    {
        dexNum: 150,
        nombre: "Mewtwo",
        tipo1: "Psychic",
        tipo2: "",
        especie: "Genetic Pokémon",
        altura: "2.0 m",
        peso: "122.0 kg",
        gruposHuevo: ["Undiscovered"],
        genero: new Genero(),
        habilidades: ["Pressure", "Unnerve"],
        stats:new Stats(,,,,,),
        velocidades:new Velocidades(null,null,null,null,null),
        atributos:new Atributos(,),
        skills:[],
        caracteristicas:[],
        evolution: ""
    },
    {
        dexNum: 151,
        nombre: "Mew",
        tipo1: "Psychic",
        tipo2: "",
        especie: "New Species Pokémon",
        altura: "0.4 m",
        peso: "4.0 kg",
        gruposHuevo: ["Undiscovered"],
        genero: new Genero(),
        habilidades: ["Synchronize"],
        stats:new Stats(,,,,,),
        velocidades:new Velocidades(null,null,null,null,null),
        atributos:new Atributos(,),
        skills:[],
        caracteristicas:[],
        evolution: ""
    }

    
    // Template
    {
        dexNum:,
        nombre:"",
        tipo1:"",
        tipo2:"",
        especie:"",
        altura:"",
        peso:"",
        gruposHuevo:[],
        genero: new Genero(),
        habilidades:[],
        stats:new Stats(,,,,,),
        velocidades:new Velocidades(null,null,null,null,null),
        atributos:new Atributos(,),
        skills:[],
        caracteristicas:[],
        evolution:""
    },
]